server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://172.19.241.28:3306/project?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: hellojenkins.bean

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
